[build-system]
requires = ["poetry-core>=1.1.0b2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "project-config"
version = "0.1.0"
description = "Reproducible configuration across projects."
authors = ["Álvaro Mondéjar Rubio <mondejar1994@gmail.com>"]
license = "BSD-3-License"
readme = "README.md"
repository = "https://github.com/mondeja/project-config"
documentation = "https://github.com/mondeja/project-config#documentation"
packages = [{ include = "project_config", from = "src" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Quality Assurance",
  "Environment :: Console",
]

[tool.poetry.urls]
"Bug tracker" = "https://github.com/mondeja/project-config/issues"

[tool.poetry.dependencies]
python = "^3.7"
# importlib.metadata.entry_points lacks 'group' argument until 3.10
importlib-metadata = { version = "*", python = "<3.10" }
importlib-metadata-argparse-version = "*"
tomli = { version = "^2", python = "<3.11" }
tomli-w = "^1"
pyjson5 = "*"
colored = "*"
tabulate = "^0.8"
typing-extensions = "^4"
jmespath = "^1"
identify = "^2"
"ruamel.yaml" = "~0.17"
appdirs = "^1"
diskcache = "^5"

[tool.poetry.group.dev.dependencies]
mondeja-bump = "*"
pre-commit = "*"

[tool.poetry.group.test.dependencies]
pytest = "^7"
pytest-cov = "^3"
pre-commit = "^2.9"
contextlib-chdir = "^1"
pytest-maybe-raises = "^0.1.1"
flask = "^2"

[tool.poetry.group.doc.dependencies]
Sphinx = "^4"
importlib-metadata = { version = "*", python = "<3.10" }
sphinx-rtd-theme = "^1"
sphinx-tabs = "~3.3"
chios = "^1"
sphinx-argparse-cli = "^1.8.3"

[tool.poetry.scripts]
project-config = "project_config.__main__:main"

[tool.poetry.plugins."project_config.plugins"]
include = "project_config.plugins.include:IncludePlugin"
jmespath = "project_config.plugins.jmespath:JMESPathPlugin"

[tool.bump]
targets = [
  { file = "pyproject.toml", regex = "(version = [\"'])(\\d+\\.\\d+\\.\\d+)([\"'])" },
  { file = "docs/install.rst", regex = "(v)(\\d+\\.\\d+\\.\\d+)" },
]

[tool.project-config]
style = [
  # Basic Python styles: use poetry
  "gh://mondeja/project-config-styles/python/base.json5",
  # Minimum Python version
  "gh://mondeja/project-config-styles/python/version/min-37.json5",
  # Double quotes: formatting with Black
  "gh://mondeja/project-config-styles/python/double-quotes.json5",
  # Maximum line length
  "gh://mondeja/project-config-styles/python/line-length-80.json5",
  # Testing styles: use pytest
  "gh://mondeja/project-config-styles/python/tests.json5",
  # Documentation styles: use Sphinx with Readthedocs theme
  "gh://mondeja/project-config-styles/python/sphinx.json5",
  "gh://mondeja/project-config-styles/python/google-docstrings.json5",
  "gh://mondeja/project-config-styles/python/readthedocs.json5",
  # Type checking with mypy
  #"../project-config-styles/python/mypy.json5",

]
cache = "1 hour"

[tool.poetry-exec-plugin.commands]
t = "pytest"
test = "pytest"
"test:all" = "pytest"
"test:show" = """pytest &&
python -c 'import webbrowser as w;w.open("http://127.0.0.1:8080")' &&
python -m http.server 8080 -b localhost -d htmlcov
"""
doc = "python -m sphinx -n -T -E -W docs docs/_build/html"
"doc:show" = """python -m sphinx -n -T -E -W docs docs/_build/html &&
python -c 'import webbrowser as w;w.open("http://127.0.0.1:8080")' &&
python -m http.server 8080 -b localhost -d docs/_build/html"""
lint = "pre-commit run -a"

[tool.pytest.ini_options]
addopts = "-s --cov=src --cov-report=html"

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "if __name__ == [\"']__main__[\"']:"]

[tool.mypy]
python_version = "3.7"
strict = true

[tool.isort]
lines_after_imports = 2
multi_line_output = 3
line_length = 79
use_parentheses = true
combine_as_imports = true
include_trailing_comma = true
known_tests = "tests"
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "TESTS", "LOCALFOLDER"]
py_version = 37
extra_standard_library = [
  "contextvars",
  "dataclasses",
  "importlib.resources",
  "importlib.metadata",
  "zoneinfo",
  "graphlib",
  "tomllib",
  "wsgiref.types",
]

[tool.black]
line-length = 80
target-version = ["py37"]

[tool.flakeheaven]
max_line_length = 80
inline_quotes = "double"
docstring_convention = "google"
pytest_parametrize_values_type = "tuple"
pytest_fixture_no_parentheses = true

[tool.flakeheaven.plugins]
pycodestyle = ["+*", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-docstrings = ["+*", "-D105", "-D107"]
flake8-executable = ["+*"]
flake8-implicit-str-concat = ["+*"]
flake8-print = ["+*"]
flake8-printf-formatting = ["+*"]
flake8-pytest-style = ["+*"]

[tool.flakeheaven.exceptions."tests/**"]
flake8-docstrings = [
  "-D100",
  "-D101",
  "-D102",
  "-D103",
  "-D107",
  "-D205",
  "-D415"
]

[tool.flakeheaven.exceptions."src/project_config/plugins/**"]
flake8-docstrings = [
  # Plugins must not add docstrings for public classes because they
  # do not have constructors, are documented docs/reference/plugins.rst
  "-D101",
  # Plugins methods are documented in docs/reference/plugins.rst
  "-D102",
  # Plugins must not document all arguments because are always repeated
  "-D417",
]
