[tool.poetry]
name = "shipout"
version = "0.1.2"
description = ""
authors = ["BlurwareAdmin <admin@blurware.com>"]

[tool.poetry.scripts]
shipout = "shipout.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.4.1"}
azure-identity = "^1.10.0"
azure-mgmt-resource = "^21.1.0"
azure-mgmt-storage = "^20.0.0"
docker = "^5.0.3"
pulumi = "^3.33.1"
azure-mgmt-authorization = "^2.0.0"
pulumi-azure-native = "^1.64.1"
pulumi-azure = "^5.10.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
