[tool.poetry]
name = "hetzner-control"
version = "0.5.0"
description = "CLI application for managing servers on the Hetzner platform"
authors = ["Hanabira <workflow.elec@gmail.com>"]
readme = "README.md"
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
typer = "^0.4.0"
rich = "^12.0.0"

[tool.poetry.scripts]
htz = "hetzner_control.cli:main"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
responses = "^0.20.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
