[tool.poetry]
name = "pprl"
version = "0.3.1"
description = "Wrapper around PPRL services provided by MDS Group Leipzig"
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
maintainers = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
license = "MIT"
readme = "README.md"
documentation = "https://pprl.gitlab.io/pprl-python-client/"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Security",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
pdoc3 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
