[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "soxaikit"
version = "0.0.0.15"
authors = [
  { name="jiabin", email="wjbthu@gmail.com" },
]
description = "soxai kit for data process"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://soxai.co.jp/"
