[tool.poetry]
name = "poetry-demo-thomas-cleary"
version = "0.5.3"
description = "Example of setting up a python package project with poetry"
license = "MIT"
authors = ["Thomas Cleary <thomasclearydev@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
poetry-demo = "poetry_demo_thomas_cleary.cli:run"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pylint = "^2.14.3"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
