[tool.poetry]
name = "gnomadapi"
version = "1.0.0"
description = "selenium wrapper to access gnomad db from the cmd"
authors = ["StephanHolgerD <stephdruk@googlemail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "4.2.0"
chromedriver-binary-auto = "0.1.2"
chromedriver-binary = "^104.0.5112"
glob2 = "^0.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
# aka entry points or console scripts for setup.py users
'gnomadAPI' = 'gnomadapi.__main__:main'